import { Injectable } from '@angular/core';

@Injectable()
export class TweetService {

  constructor() { }
private tweetList={
  "d" : {
  "results": [{
    "createdAt": "Jan 20, 2018 10:49:51 AM",
    "id": 954584233875419136,
    "text": "RT @btsportcricket: \"I thought you said it was apes, mate?\"\n\n\"Nope. Definitely Super Mario Bros.\"\n\n\"Damn\"\n\nNothing to see here ?\n\n#AUSvENG…",
    "displayTextRangeStart": -1,
    "displayTextRangeEnd": -1,
    "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
    "isTruncated": false,
    "inReplyToStatusId": -1,
    "inReplyToUserId": -1,
    "isFavorited": false,
    "isRetweeted": false,
    "favoriteCount": 0,
    "retweetCount": 167,
    "isPossiblySensitive": false,
    "lang": "en",
    "contributorsIDs": [],
    "retweetedStatus": {
        "createdAt": "Jan 19, 2018 9:23:05 AM",
        "id": 954200011197296640,
        "text": "\"I thought you said it was apes, mate?\"\n\n\"Nope. Definitely Super Mario Bros.\"\n\n\"Damn\"\n\nNothing to see here ?… https://t.co/AvJ2dqP1c7",
        "displayTextRangeStart": -1,
        "displayTextRangeEnd": -1,
        "source": "<a href=\"https://about.twitter.com/products/tweetdeck\" rel=\"nofollow\">TweetDeck</a>",
        "isTruncated": true,
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "isFavorited": false,
        "isRetweeted": false,
        "favoriteCount": 596,
        "retweetCount": 167,
        "isPossiblySensitive": false,
        "lang": "en",
        "contributorsIDs": [],
        "userMentionEntities": [],
        "urlEntities": [{
            "url": "https://t.co/AvJ2dqP1c7",
            "expandedURL": "https://twitter.com/i/web/status/954200011197296640",
            "displayURL": "twitter.com/i/web/status/9…",
            "start": 110,
            "end": 133
        }],
        "hashtagEntities": [],
        "mediaEntities": [],
        "symbolEntities": [],
        "currentUserRetweetId": -1,
        "user": {
            "id": 2294278176,
            "name": "Cricket on BT Sport",
            "screenName": "btsportcricket",
            "location": "The Gabba",
            "description": "Watch the ODI series between England and Australia on BT Sport. Also the home of the @BBL!",
            "descriptionURLEntities": [],
            "urlEntity": {
                "url": "https://t.co/Flc9k1FSfd",
                "expandedURL": "http://sport.bt.com/cricket-01364050608536",
                "displayURL": "sport.bt.com/cricket-013640…",
                "start": 0,
                "end": 23
            },
            "isContributorsEnabled": false,
            "profileImageUrl": "http://pbs.twimg.com/profile_images/950730480139333632/nutJD8hz_normal.jpg",
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/950730480139333632/nutJD8hz_normal.jpg",
            "isDefaultProfileImage": false,
            "url": "https://t.co/Flc9k1FSfd",
            "isProtected": false,
            "followersCount": 44554,
            "profileBackgroundColor": "DADEE1",
            "profileTextColor": "333333",
            "profileLinkColor": "FF0000",
            "profileSidebarFillColor": "DDEEF6",
            "profileSidebarBorderColor": "FFFFFF",
            "profileUseBackgroundImage": true,
            "isDefaultProfile": false,
            "showAllInlineMedia": false,
            "friendsCount": 277,
            "createdAt": "Jan 16, 2014 4:43:49 PM",
            "favouritesCount": 965,
            "utcOffset": 0,
            "timeZone": "London",
            "profileBackgroundImageUrl": "http://pbs.twimg.com/profile_background_images/431758204016406528/QEZ9zTOo.jpeg",
            "profileBackgroundImageUrlHttps": "https://pbs.twimg.com/profile_background_images/431758204016406528/QEZ9zTOo.jpeg",
            "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/2294278176/1515928782",
            "profileBackgroundTiled": false,
            "lang": "en",
            "statusesCount": 3822,
            "isGeoEnabled": false,
            "isVerified": true,
            "translator": false,
            "listedCount": 212,
            "isFollowRequestSent": false
        },
        "quotedStatusId": -1
    },
    "userMentionEntities": [{
        "name": "Cricket on BT Sport",
        "screenName": "btsportcricket",
        "id": 2294278176,
        "start": 3,
        "end": 18
    }],
    "urlEntities": [],
    "hashtagEntities": [{
        "text": "AUSvENG",
        "start": 130,
        "end": 138
    }],
    "mediaEntities": [],
    "symbolEntities": [],
    "currentUserRetweetId": -1,
    "user": {
        "id": 818001095033257984,
        "name": "Heavenly ?",
        "screenName": "Pizza__Heart",
        "location": "In our heart ? ",
        "description": "? ? ? ? ? ? ? ? ? ? ? ?",
        "descriptionURLEntities": [],
        "isContributorsEnabled": false,
        "profileImageUrl": "http://pbs.twimg.com/profile_images/949011478501146625/cq_sOLXa_normal.jpg",
        "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/949011478501146625/cq_sOLXa_normal.jpg",
        "isDefaultProfileImage": false,
        "isProtected": false,
        "followersCount": 542,
        "profileBackgroundColor": "000000",
        "profileTextColor": "000000",
        "profileLinkColor": "19CF86",
        "profileSidebarFillColor": "000000",
        "profileSidebarBorderColor": "000000",
        "profileUseBackgroundImage": false,
        "isDefaultProfile": false,
        "showAllInlineMedia": false,
        "friendsCount": 96,
        "createdAt": "Jan 8, 2017 1:17:13 PM",
        "favouritesCount": 9795,
        "utcOffset": -28800,
        "timeZone": "Pacific Time (US & Canada)",
        "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/818001095033257984/1515096663",
        "profileBackgroundTiled": false,
        "lang": "en",
        "statusesCount": 1730,
        "isGeoEnabled": true,
        "isVerified": false,
        "translator": false,
        "listedCount": 6,
        "isFollowRequestSent": false
    },
    "quotedStatusId": -1
}, {
    "createdAt": "Jan 20, 2018 10:44:14 AM",
    "id": 954582819560460289,
    "text": "RT @MichaelVaughan: That’s as good a bowling and captaincy display that I have seen from England with the White ball......  #AUSvENG",
    "displayTextRangeStart": -1,
    "displayTextRangeEnd": -1,
    "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
    "isTruncated": false,
    "inReplyToStatusId": -1,
    "inReplyToUserId": -1,
    "isFavorited": false,
    "isRetweeted": false,
    "favoriteCount": 0,
    "retweetCount": 47,
    "isPossiblySensitive": false,
    "lang": "en",
    "contributorsIDs": [],
    "retweetedStatus": {
        "createdAt": "Jan 19, 2018 12:41:01 PM",
        "id": 954249822982336513,
        "text": "That’s as good a bowling and captaincy display that I have seen from England with the White ball......  #AUSvENG",
        "displayTextRangeStart": -1,
        "displayTextRangeEnd": -1,
        "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
        "isTruncated": false,
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "isFavorited": false,
        "isRetweeted": false,
        "favoriteCount": 625,
        "retweetCount": 47,
        "isPossiblySensitive": false,
        "lang": "en",
        "contributorsIDs": [],
        "userMentionEntities": [],
        "urlEntities": [],
        "hashtagEntities": [{
            "text": "AUSvENG",
            "start": 104,
            "end": 112
        }],
        "mediaEntities": [],
        "symbolEntities": [],
        "currentUserRetweetId": -1,
        "user": {
            "id": 97893963,
            "name": "Michael Vaughan",
            "screenName": "MichaelVaughan",
            "location": "iPhone: 0.000000,0.000000",
            "description": "Manchester born sheffield lad..Instagram MichaelVaughan ..My Protein Ambassador .. https://t.co/plRHWP0Bej. add VAUGHAN10 for discount ..",
            "descriptionURLEntities": [{
                "url": "https://t.co/plRHWP0Bej",
                "expandedURL": "http://bit.do/Vaughan",
                "displayURL": "bit.do/Vaughan",
                "start": 83,
                "end": 106
            }],
            "isContributorsEnabled": false,
            "profileImageUrl": "http://pbs.twimg.com/profile_images/905461608914321414/ns0-VQGS_normal.jpg",
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/905461608914321414/ns0-VQGS_normal.jpg",
            "isDefaultProfileImage": false,
            "isProtected": false,
            "followersCount": 1108428,
            "profileBackgroundColor": "C0DEED",
            "profileTextColor": "333333",
            "profileLinkColor": "1DA1F2",
            "profileSidebarFillColor": "DDEEF6",
            "profileSidebarBorderColor": "C0DEED",
            "profileUseBackgroundImage": true,
            "isDefaultProfile": true,
            "showAllInlineMedia": false,
            "friendsCount": 1156,
            "createdAt": "Dec 19, 2009 6:29:58 PM",
            "favouritesCount": 3041,
            "utcOffset": -1,
            "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
            "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
            "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/97893963/1396338851",
            "profileBackgroundTiled": false,
            "lang": "en",
            "statusesCount": 33710,
            "isGeoEnabled": false,
            "isVerified": true,
            "translator": false,
            "listedCount": 4274,
            "isFollowRequestSent": false
        },
        "quotedStatusId": -1
    },
    "userMentionEntities": [{
        "name": "Michael Vaughan",
        "screenName": "MichaelVaughan",
        "id": 97893963,
        "start": 3,
        "end": 18
    }],
    "urlEntities": [],
    "hashtagEntities": [{
        "text": "AUSvENG",
        "start": 124,
        "end": 132
    }],
    "mediaEntities": [],
    "symbolEntities": [],
    "currentUserRetweetId": -1,
    "user": {
        "id": 3197824010,
        "name": "afxaal  hayat",
        "screenName": "afzalhayat0103",
        "location": "Aligarh ",
        "description": "Calling someone stupid doesn't make you any smarter.",
        "descriptionURLEntities": [],
        "isContributorsEnabled": false,
        "profileImageUrl": "http://pbs.twimg.com/profile_images/771695810954293248/cypvGDzD_normal.jpg",
        "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/771695810954293248/cypvGDzD_normal.jpg",
        "isDefaultProfileImage": false,
        "isProtected": false,
        "followersCount": 279,
        "profileBackgroundColor": "C0DEED",
        "profileTextColor": "333333",
        "profileLinkColor": "1DA1F2",
        "profileSidebarFillColor": "DDEEF6",
        "profileSidebarBorderColor": "C0DEED",
        "profileUseBackgroundImage": true,
        "isDefaultProfile": true,
        "showAllInlineMedia": false,
        "friendsCount": 1294,
        "createdAt": "May 17, 2015 1:11:34 AM",
        "favouritesCount": 159,
        "utcOffset": -1,
        "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/3197824010/1472822535",
        "profileBackgroundTiled": false,
        "lang": "en",
        "statusesCount": 24602,
        "isGeoEnabled": false,
        "isVerified": false,
        "translator": false,
        "listedCount": 10,
        "isFollowRequestSent": false
    },
    "quotedStatusId": -1
}, {
    "createdAt": "Jan 20, 2018 9:28:53 AM",
    "id": 954563860392013824,
    "text": "RT @btsportcricket: \"I thought you said it was apes, mate?\"\n\n\"Nope. Definitely Super Mario Bros.\"\n\n\"Damn\"\n\nNothing to see here ?\n\n#AUSvENG…",
    "displayTextRangeStart": -1,
    "displayTextRangeEnd": -1,
    "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
    "isTruncated": false,
    "inReplyToStatusId": -1,
    "inReplyToUserId": -1,
    "isFavorited": false,
    "isRetweeted": false,
    "favoriteCount": 0,
    "retweetCount": 167,
    "isPossiblySensitive": false,
    "lang": "en",
    "contributorsIDs": [],
    "retweetedStatus": {
        "createdAt": "Jan 19, 2018 9:23:05 AM",
        "id": 954200011197296640,
        "text": "\"I thought you said it was apes, mate?\"\n\n\"Nope. Definitely Super Mario Bros.\"\n\n\"Damn\"\n\nNothing to see here ?… https://t.co/AvJ2dqP1c7",
        "displayTextRangeStart": -1,
        "displayTextRangeEnd": -1,
        "source": "<a href=\"https://about.twitter.com/products/tweetdeck\" rel=\"nofollow\">TweetDeck</a>",
        "isTruncated": true,
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "isFavorited": false,
        "isRetweeted": false,
        "favoriteCount": 596,
        "retweetCount": 167,
        "isPossiblySensitive": false,
        "lang": "en",
        "contributorsIDs": [],
        "userMentionEntities": [],
        "urlEntities": [{
            "url": "https://t.co/AvJ2dqP1c7",
            "expandedURL": "https://twitter.com/i/web/status/954200011197296640",
            "displayURL": "twitter.com/i/web/status/9…",
            "start": 110,
            "end": 133
        }],
        "hashtagEntities": [],
        "mediaEntities": [],
        "symbolEntities": [],
        "currentUserRetweetId": -1,
        "user": {
            "id": 2294278176,
            "name": "Cricket on BT Sport",
            "screenName": "btsportcricket",
            "location": "The Gabba",
            "description": "Watch the ODI series between England and Australia on BT Sport. Also the home of the @BBL!",
            "descriptionURLEntities": [],
            "urlEntity": {
                "url": "https://t.co/Flc9k1FSfd",
                "expandedURL": "http://sport.bt.com/cricket-01364050608536",
                "displayURL": "sport.bt.com/cricket-013640…",
                "start": 0,
                "end": 23
            },
            "isContributorsEnabled": false,
            "profileImageUrl": "http://pbs.twimg.com/profile_images/950730480139333632/nutJD8hz_normal.jpg",
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/950730480139333632/nutJD8hz_normal.jpg",
            "isDefaultProfileImage": false,
            "url": "https://t.co/Flc9k1FSfd",
            "isProtected": false,
            "followersCount": 44554,
            "profileBackgroundColor": "DADEE1",
            "profileTextColor": "333333",
            "profileLinkColor": "FF0000",
            "profileSidebarFillColor": "DDEEF6",
            "profileSidebarBorderColor": "FFFFFF",
            "profileUseBackgroundImage": true,
            "isDefaultProfile": false,
            "showAllInlineMedia": false,
            "friendsCount": 277,
            "createdAt": "Jan 16, 2014 4:43:49 PM",
            "favouritesCount": 965,
            "utcOffset": 0,
            "timeZone": "London",
            "profileBackgroundImageUrl": "http://pbs.twimg.com/profile_background_images/431758204016406528/QEZ9zTOo.jpeg",
            "profileBackgroundImageUrlHttps": "https://pbs.twimg.com/profile_background_images/431758204016406528/QEZ9zTOo.jpeg",
            "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/2294278176/1515928782",
            "profileBackgroundTiled": false,
            "lang": "en",
            "statusesCount": 3822,
            "isGeoEnabled": false,
            "isVerified": true,
            "translator": false,
            "listedCount": 212,
            "isFollowRequestSent": false
        },
        "quotedStatusId": -1
    },
    "userMentionEntities": [{
        "name": "Cricket on BT Sport",
        "screenName": "btsportcricket",
        "id": 2294278176,
        "start": 3,
        "end": 18
    }],
    "urlEntities": [],
    "hashtagEntities": [{
        "text": "AUSvENG",
        "start": 130,
        "end": 138
    }],
    "mediaEntities": [],
    "symbolEntities": [],
    "currentUserRetweetId": -1,
    "user": {
        "id": 1782534222,
        "name": "Stable Genius",
        "screenName": "albeesko",
        "location": "NJIT",
        "description": "A lifetime of glory is worth a moment of pain",
        "descriptionURLEntities": [],
        "isContributorsEnabled": false,
        "profileImageUrl": "http://pbs.twimg.com/profile_images/945735959693484032/N_Mr2N6S_normal.jpg",
        "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/945735959693484032/N_Mr2N6S_normal.jpg",
        "isDefaultProfileImage": false,
        "isProtected": false,
        "followersCount": 320,
        "profileBackgroundColor": "C0DEED",
        "profileTextColor": "333333",
        "profileLinkColor": "1DA1F2",
        "profileSidebarFillColor": "DDEEF6",
        "profileSidebarBorderColor": "C0DEED",
        "profileUseBackgroundImage": true,
        "isDefaultProfile": true,
        "showAllInlineMedia": false,
        "friendsCount": 296,
        "createdAt": "Sep 8, 2013 4:06:34 AM",
        "favouritesCount": 4148,
        "utcOffset": -1,
        "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/1782534222/1512017029",
        "profileBackgroundTiled": false,
        "lang": "en",
        "statusesCount": 14231,
        "isGeoEnabled": false,
        "isVerified": false,
        "translator": false,
        "listedCount": 0,
        "isFollowRequestSent": false
    },
    "quotedStatusId": -1
}, {
    "createdAt": "Jan 20, 2018 8:34:09 AM",
    "id": 954550084397498368,
    "text": "RT @Cricketpolls3: Which batter has impressed you the most in the recent couple 9f matches in #AUSvENG ?",
    "displayTextRangeStart": -1,
    "displayTextRangeEnd": -1,
    "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
    "isTruncated": false,
    "inReplyToStatusId": -1,
    "inReplyToUserId": -1,
    "isFavorited": false,
    "isRetweeted": false,
    "favoriteCount": 0,
    "retweetCount": 2,
    "isPossiblySensitive": false,
    "lang": "en",
    "contributorsIDs": [],
    "retweetedStatus": {
        "createdAt": "Jan 19, 2018 7:00:58 PM",
        "id": 954345439259578368,
        "text": "Which batter has impressed you the most in the recent couple 9f matches in #AUSvENG ?",
        "displayTextRangeStart": -1,
        "displayTextRangeEnd": -1,
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
        "isTruncated": false,
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "isFavorited": false,
        "isRetweeted": false,
        "favoriteCount": 1,
        "retweetCount": 2,
        "isPossiblySensitive": false,
        "lang": "en",
        "contributorsIDs": [],
        "userMentionEntities": [],
        "urlEntities": [],
        "hashtagEntities": [{
            "text": "AUSvENG",
            "start": 75,
            "end": 83
        }],
        "mediaEntities": [],
        "symbolEntities": [],
        "currentUserRetweetId": -1,
        "user": {
            "id": 923387282849009665,
            "name": "Cricket polls",
            "screenName": "Cricketpolls3",
            "location": "Where that six landed",
            "description": "Keep scrolling down there are #polls waiting for you..\nFollow us for Polls,#scores,latest #cricket #events,#information,#talk,#facts and alot more..",
            "descriptionURLEntities": [],
            "isContributorsEnabled": false,
            "profileImageUrl": "http://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
            "isDefaultProfileImage": false,
            "isProtected": false,
            "followersCount": 135,
            "profileBackgroundColor": "F5F8FA",
            "profileTextColor": "333333",
            "profileLinkColor": "1DA1F2",
            "profileSidebarFillColor": "DDEEF6",
            "profileSidebarBorderColor": "C0DEED",
            "profileUseBackgroundImage": true,
            "isDefaultProfile": true,
            "showAllInlineMedia": false,
            "friendsCount": 79,
            "createdAt": "Oct 26, 2017 8:44:18 AM",
            "favouritesCount": 945,
            "utcOffset": -1,
            "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/923387282849009665/1515905099",
            "profileBackgroundTiled": false,
            "lang": "en",
            "statusesCount": 1111,
            "isGeoEnabled": false,
            "isVerified": false,
            "translator": false,
            "listedCount": 1,
            "isFollowRequestSent": false
        },
        "quotedStatusId": -1
    },
    "userMentionEntities": [{
        "name": "Cricket polls",
        "screenName": "Cricketpolls3",
        "id": 923387282849009665,
        "start": 3,
        "end": 17
    }],
    "urlEntities": [],
    "hashtagEntities": [{
        "text": "AUSvENG",
        "start": 94,
        "end": 102
    }],
    "mediaEntities": [],
    "symbolEntities": [],
    "currentUserRetweetId": -1,
    "user": {
        "id": 3268344722,
        "name": "Girish sharma",
        "screenName": "Girishs10883782",
        "location": "Jaipur, India",
        "description": "Chech out @cricketpolls3 !!",
        "descriptionURLEntities": [],
        "urlEntity": {
            "url": "https://t.co/YTs1tCotRH",
            "expandedURL": "http://anastrogeek.WordPress.com",
            "displayURL": "anastrogeek.WordPress.com",
            "start": 0,
            "end": 23
        },
        "isContributorsEnabled": false,
        "profileImageUrl": "http://pbs.twimg.com/profile_images/867025617937674240/Nb0wpYya_normal.jpg",
        "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/867025617937674240/Nb0wpYya_normal.jpg",
        "isDefaultProfileImage": false,
        "url": "https://t.co/YTs1tCotRH",
        "isProtected": false,
        "followersCount": 36,
        "profileBackgroundColor": "C0DEED",
        "profileTextColor": "333333",
        "profileLinkColor": "1DA1F2",
        "profileSidebarFillColor": "DDEEF6",
        "profileSidebarBorderColor": "C0DEED",
        "profileUseBackgroundImage": true,
        "isDefaultProfile": true,
        "showAllInlineMedia": false,
        "friendsCount": 218,
        "createdAt": "Jul 4, 2015 11:48:14 PM",
        "favouritesCount": 1361,
        "utcOffset": -1,
        "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/3268344722/1495549988",
        "profileBackgroundTiled": false,
        "lang": "en",
        "statusesCount": 458,
        "isGeoEnabled": false,
        "isVerified": false,
        "translator": false,
        "listedCount": 0,
        "isFollowRequestSent": false
    },
    "quotedStatusId": -1
}, {
    "createdAt": "Jan 20, 2018 8:31:48 AM",
    "id": 954549491461320704,
    "text": "RT @Cricketpolls3: Which batter has impressed you the most in the recent couple 9f matches in #AUSvENG ?",
    "displayTextRangeStart": -1,
    "displayTextRangeEnd": -1,
    "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
    "isTruncated": false,
    "inReplyToStatusId": -1,
    "inReplyToUserId": -1,
    "isFavorited": false,
    "isRetweeted": false,
    "favoriteCount": 0,
    "retweetCount": 2,
    "isPossiblySensitive": false,
    "lang": "en",
    "contributorsIDs": [],
    "retweetedStatus": {
        "createdAt": "Jan 19, 2018 7:00:58 PM",
        "id": 954345439259578368,
        "text": "Which batter has impressed you the most in the recent couple 9f matches in #AUSvENG ?",
        "displayTextRangeStart": -1,
        "displayTextRangeEnd": -1,
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
        "isTruncated": false,
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "isFavorited": false,
        "isRetweeted": false,
        "favoriteCount": 1,
        "retweetCount": 2,
        "isPossiblySensitive": false,
        "lang": "en",
        "contributorsIDs": [],
        "userMentionEntities": [],
        "urlEntities": [],
        "hashtagEntities": [{
            "text": "AUSvENG",
            "start": 75,
            "end": 83
        }],
        "mediaEntities": [],
        "symbolEntities": [],
        "currentUserRetweetId": -1,
        "user": {
            "id": 923387282849009665,
            "name": "Cricket polls",
            "screenName": "Cricketpolls3",
            "location": "Where that six landed",
            "description": "Keep scrolling down there are #polls waiting for you..\nFollow us for Polls,#scores,latest #cricket #events,#information,#talk,#facts and alot more..",
            "descriptionURLEntities": [],
            "isContributorsEnabled": false,
            "profileImageUrl": "http://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
            "isDefaultProfileImage": false,
            "isProtected": false,
            "followersCount": 135,
            "profileBackgroundColor": "F5F8FA",
            "profileTextColor": "333333",
            "profileLinkColor": "1DA1F2",
            "profileSidebarFillColor": "DDEEF6",
            "profileSidebarBorderColor": "C0DEED",
            "profileUseBackgroundImage": true,
            "isDefaultProfile": true,
            "showAllInlineMedia": false,
            "friendsCount": 79,
            "createdAt": "Oct 26, 2017 8:44:18 AM",
            "favouritesCount": 945,
            "utcOffset": -1,
            "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/923387282849009665/1515905099",
            "profileBackgroundTiled": false,
            "lang": "en",
            "statusesCount": 1111,
            "isGeoEnabled": false,
            "isVerified": false,
            "translator": false,
            "listedCount": 1,
            "isFollowRequestSent": false
        },
        "quotedStatusId": -1
    },
    "userMentionEntities": [{
        "name": "Cricket polls",
        "screenName": "Cricketpolls3",
        "id": 923387282849009665,
        "start": 3,
        "end": 17
    }],
    "urlEntities": [],
    "hashtagEntities": [{
        "text": "AUSvENG",
        "start": 94,
        "end": 102
    }],
    "mediaEntities": [],
    "symbolEntities": [],
    "currentUserRetweetId": -1,
    "user": {
        "id": 923387282849009665,
        "name": "Cricket polls",
        "screenName": "Cricketpolls3",
        "location": "Where that six landed",
        "description": "Keep scrolling down there are #polls waiting for you..\nFollow us for Polls,#scores,latest #cricket #events,#information,#talk,#facts and alot more..",
        "descriptionURLEntities": [],
        "isContributorsEnabled": false,
        "profileImageUrl": "http://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
        "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
        "isDefaultProfileImage": false,
        "isProtected": false,
        "followersCount": 135,
        "profileBackgroundColor": "F5F8FA",
        "profileTextColor": "333333",
        "profileLinkColor": "1DA1F2",
        "profileSidebarFillColor": "DDEEF6",
        "profileSidebarBorderColor": "C0DEED",
        "profileUseBackgroundImage": true,
        "isDefaultProfile": true,
        "showAllInlineMedia": false,
        "friendsCount": 79,
        "createdAt": "Oct 26, 2017 8:44:18 AM",
        "favouritesCount": 945,
        "utcOffset": -1,
        "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/923387282849009665/1515905099",
        "profileBackgroundTiled": false,
        "lang": "en",
        "statusesCount": 1111,
        "isGeoEnabled": false,
        "isVerified": false,
        "translator": false,
        "listedCount": 1,
        "isFollowRequestSent": false
    },
    "quotedStatusId": -1
},
{
    "createdAt": "Jan 20, 2018 10:49:51 AM",
    "id": 954584233875419136,
    "text": "RT @btsportcricket: \"I thought you said it was apes, mate?\"\n\n\"Nope. Definitely Super Mario Bros.\"\n\n\"Damn\"\n\nNothing to see here ?\n\n#AUSvENG…",
    "displayTextRangeStart": -1,
    "displayTextRangeEnd": -1,
    "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
    "isTruncated": false,
    "inReplyToStatusId": -1,
    "inReplyToUserId": -1,
    "isFavorited": false,
    "isRetweeted": false,
    "favoriteCount": 0,
    "retweetCount": 167,
    "isPossiblySensitive": false,
    "lang": "en",
    "contributorsIDs": [],
    "retweetedStatus": {
        "createdAt": "Jan 19, 2018 9:23:05 AM",
        "id": 954200011197296640,
        "text": "\"I thought you said it was apes, mate?\"\n\n\"Nope. Definitely Super Mario Bros.\"\n\n\"Damn\"\n\nNothing to see here ?… https://t.co/AvJ2dqP1c7",
        "displayTextRangeStart": -1,
        "displayTextRangeEnd": -1,
        "source": "<a href=\"https://about.twitter.com/products/tweetdeck\" rel=\"nofollow\">TweetDeck</a>",
        "isTruncated": true,
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "isFavorited": false,
        "isRetweeted": false,
        "favoriteCount": 596,
        "retweetCount": 167,
        "isPossiblySensitive": false,
        "lang": "en",
        "contributorsIDs": [],
        "userMentionEntities": [],
        "urlEntities": [{
            "url": "https://t.co/AvJ2dqP1c7",
            "expandedURL": "https://twitter.com/i/web/status/954200011197296640",
            "displayURL": "twitter.com/i/web/status/9…",
            "start": 110,
            "end": 133
        }],
        "hashtagEntities": [],
        "mediaEntities": [],
        "symbolEntities": [],
        "currentUserRetweetId": -1,
        "user": {
            "id": 2294278176,
            "name": "Cricket on BT Sport",
            "screenName": "btsportcricket",
            "location": "The Gabba",
            "description": "Watch the ODI series between England and Australia on BT Sport. Also the home of the @BBL!",
            "descriptionURLEntities": [],
            "urlEntity": {
                "url": "https://t.co/Flc9k1FSfd",
                "expandedURL": "http://sport.bt.com/cricket-01364050608536",
                "displayURL": "sport.bt.com/cricket-013640…",
                "start": 0,
                "end": 23
            },
            "isContributorsEnabled": false,
            "profileImageUrl": "http://pbs.twimg.com/profile_images/950730480139333632/nutJD8hz_normal.jpg",
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/950730480139333632/nutJD8hz_normal.jpg",
            "isDefaultProfileImage": false,
            "url": "https://t.co/Flc9k1FSfd",
            "isProtected": false,
            "followersCount": 44554,
            "profileBackgroundColor": "DADEE1",
            "profileTextColor": "333333",
            "profileLinkColor": "FF0000",
            "profileSidebarFillColor": "DDEEF6",
            "profileSidebarBorderColor": "FFFFFF",
            "profileUseBackgroundImage": true,
            "isDefaultProfile": false,
            "showAllInlineMedia": false,
            "friendsCount": 277,
            "createdAt": "Jan 16, 2014 4:43:49 PM",
            "favouritesCount": 965,
            "utcOffset": 0,
            "timeZone": "London",
            "profileBackgroundImageUrl": "http://pbs.twimg.com/profile_background_images/431758204016406528/QEZ9zTOo.jpeg",
            "profileBackgroundImageUrlHttps": "https://pbs.twimg.com/profile_background_images/431758204016406528/QEZ9zTOo.jpeg",
            "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/2294278176/1515928782",
            "profileBackgroundTiled": false,
            "lang": "en",
            "statusesCount": 3822,
            "isGeoEnabled": false,
            "isVerified": true,
            "translator": false,
            "listedCount": 212,
            "isFollowRequestSent": false
        },
        "quotedStatusId": -1
    },
    "userMentionEntities": [{
        "name": "Cricket on BT Sport",
        "screenName": "btsportcricket",
        "id": 2294278176,
        "start": 3,
        "end": 18
    }],
    "urlEntities": [],
    "hashtagEntities": [{
        "text": "AUSvENG",
        "start": 130,
        "end": 138
    }],
    "mediaEntities": [],
    "symbolEntities": [],
    "currentUserRetweetId": -1,
    "user": {
        "id": 818001095033257984,
        "name": "Heavenly ?",
        "screenName": "Pizza__Heart",
        "location": "In our heart ? ",
        "description": "? ? ? ? ? ? ? ? ? ? ? ?",
        "descriptionURLEntities": [],
        "isContributorsEnabled": false,
        "profileImageUrl": "http://pbs.twimg.com/profile_images/949011478501146625/cq_sOLXa_normal.jpg",
        "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/949011478501146625/cq_sOLXa_normal.jpg",
        "isDefaultProfileImage": false,
        "isProtected": false,
        "followersCount": 542,
        "profileBackgroundColor": "000000",
        "profileTextColor": "000000",
        "profileLinkColor": "19CF86",
        "profileSidebarFillColor": "000000",
        "profileSidebarBorderColor": "000000",
        "profileUseBackgroundImage": false,
        "isDefaultProfile": false,
        "showAllInlineMedia": false,
        "friendsCount": 96,
        "createdAt": "Jan 8, 2017 1:17:13 PM",
        "favouritesCount": 9795,
        "utcOffset": -28800,
        "timeZone": "Pacific Time (US & Canada)",
        "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/818001095033257984/1515096663",
        "profileBackgroundTiled": false,
        "lang": "en",
        "statusesCount": 1730,
        "isGeoEnabled": true,
        "isVerified": false,
        "translator": false,
        "listedCount": 6,
        "isFollowRequestSent": false
    },
    "quotedStatusId": -1
}, {
    "createdAt": "Jan 20, 2018 10:44:14 AM",
    "id": 954582819560460289,
    "text": "RT @MichaelVaughan: That’s as good a bowling and captaincy display that I have seen from England with the White ball......  #AUSvENG",
    "displayTextRangeStart": -1,
    "displayTextRangeEnd": -1,
    "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
    "isTruncated": false,
    "inReplyToStatusId": -1,
    "inReplyToUserId": -1,
    "isFavorited": false,
    "isRetweeted": false,
    "favoriteCount": 0,
    "retweetCount": 47,
    "isPossiblySensitive": false,
    "lang": "en",
    "contributorsIDs": [],
    "retweetedStatus": {
        "createdAt": "Jan 19, 2018 12:41:01 PM",
        "id": 954249822982336513,
        "text": "That’s as good a bowling and captaincy display that I have seen from England with the White ball......  #AUSvENG",
        "displayTextRangeStart": -1,
        "displayTextRangeEnd": -1,
        "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
        "isTruncated": false,
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "isFavorited": false,
        "isRetweeted": false,
        "favoriteCount": 625,
        "retweetCount": 47,
        "isPossiblySensitive": false,
        "lang": "en",
        "contributorsIDs": [],
        "userMentionEntities": [],
        "urlEntities": [],
        "hashtagEntities": [{
            "text": "AUSvENG",
            "start": 104,
            "end": 112
        }],
        "mediaEntities": [],
        "symbolEntities": [],
        "currentUserRetweetId": -1,
        "user": {
            "id": 97893963,
            "name": "Michael Vaughan",
            "screenName": "MichaelVaughan",
            "location": "iPhone: 0.000000,0.000000",
            "description": "Manchester born sheffield lad..Instagram MichaelVaughan ..My Protein Ambassador .. https://t.co/plRHWP0Bej. add VAUGHAN10 for discount ..",
            "descriptionURLEntities": [{
                "url": "https://t.co/plRHWP0Bej",
                "expandedURL": "http://bit.do/Vaughan",
                "displayURL": "bit.do/Vaughan",
                "start": 83,
                "end": 106
            }],
            "isContributorsEnabled": false,
            "profileImageUrl": "http://pbs.twimg.com/profile_images/905461608914321414/ns0-VQGS_normal.jpg",
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/905461608914321414/ns0-VQGS_normal.jpg",
            "isDefaultProfileImage": false,
            "isProtected": false,
            "followersCount": 1108428,
            "profileBackgroundColor": "C0DEED",
            "profileTextColor": "333333",
            "profileLinkColor": "1DA1F2",
            "profileSidebarFillColor": "DDEEF6",
            "profileSidebarBorderColor": "C0DEED",
            "profileUseBackgroundImage": true,
            "isDefaultProfile": true,
            "showAllInlineMedia": false,
            "friendsCount": 1156,
            "createdAt": "Dec 19, 2009 6:29:58 PM",
            "favouritesCount": 3041,
            "utcOffset": -1,
            "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
            "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
            "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/97893963/1396338851",
            "profileBackgroundTiled": false,
            "lang": "en",
            "statusesCount": 33710,
            "isGeoEnabled": false,
            "isVerified": true,
            "translator": false,
            "listedCount": 4274,
            "isFollowRequestSent": false
        },
        "quotedStatusId": -1
    },
    "userMentionEntities": [{
        "name": "Michael Vaughan",
        "screenName": "MichaelVaughan",
        "id": 97893963,
        "start": 3,
        "end": 18
    }],
    "urlEntities": [],
    "hashtagEntities": [{
        "text": "AUSvENG",
        "start": 124,
        "end": 132
    }],
    "mediaEntities": [],
    "symbolEntities": [],
    "currentUserRetweetId": -1,
    "user": {
        "id": 3197824010,
        "name": "afxaal  hayat",
        "screenName": "afzalhayat0103",
        "location": "Aligarh ",
        "description": "Calling someone stupid doesn't make you any smarter.",
        "descriptionURLEntities": [],
        "isContributorsEnabled": false,
        "profileImageUrl": "http://pbs.twimg.com/profile_images/771695810954293248/cypvGDzD_normal.jpg",
        "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/771695810954293248/cypvGDzD_normal.jpg",
        "isDefaultProfileImage": false,
        "isProtected": false,
        "followersCount": 279,
        "profileBackgroundColor": "C0DEED",
        "profileTextColor": "333333",
        "profileLinkColor": "1DA1F2",
        "profileSidebarFillColor": "DDEEF6",
        "profileSidebarBorderColor": "C0DEED",
        "profileUseBackgroundImage": true,
        "isDefaultProfile": true,
        "showAllInlineMedia": false,
        "friendsCount": 1294,
        "createdAt": "May 17, 2015 1:11:34 AM",
        "favouritesCount": 159,
        "utcOffset": -1,
        "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/3197824010/1472822535",
        "profileBackgroundTiled": false,
        "lang": "en",
        "statusesCount": 24602,
        "isGeoEnabled": false,
        "isVerified": false,
        "translator": false,
        "listedCount": 10,
        "isFollowRequestSent": false
    },
    "quotedStatusId": -1
}, {
    "createdAt": "Jan 20, 2018 9:28:53 AM",
    "id": 954563860392013824,
    "text": "RT @btsportcricket: \"I thought you said it was apes, mate?\"\n\n\"Nope. Definitely Super Mario Bros.\"\n\n\"Damn\"\n\nNothing to see here ?\n\n#AUSvENG…",
    "displayTextRangeStart": -1,
    "displayTextRangeEnd": -1,
    "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
    "isTruncated": false,
    "inReplyToStatusId": -1,
    "inReplyToUserId": -1,
    "isFavorited": false,
    "isRetweeted": false,
    "favoriteCount": 0,
    "retweetCount": 167,
    "isPossiblySensitive": false,
    "lang": "en",
    "contributorsIDs": [],
    "retweetedStatus": {
        "createdAt": "Jan 19, 2018 9:23:05 AM",
        "id": 954200011197296640,
        "text": "\"I thought you said it was apes, mate?\"\n\n\"Nope. Definitely Super Mario Bros.\"\n\n\"Damn\"\n\nNothing to see here ?… https://t.co/AvJ2dqP1c7",
        "displayTextRangeStart": -1,
        "displayTextRangeEnd": -1,
        "source": "<a href=\"https://about.twitter.com/products/tweetdeck\" rel=\"nofollow\">TweetDeck</a>",
        "isTruncated": true,
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "isFavorited": false,
        "isRetweeted": false,
        "favoriteCount": 596,
        "retweetCount": 167,
        "isPossiblySensitive": false,
        "lang": "en",
        "contributorsIDs": [],
        "userMentionEntities": [],
        "urlEntities": [{
            "url": "https://t.co/AvJ2dqP1c7",
            "expandedURL": "https://twitter.com/i/web/status/954200011197296640",
            "displayURL": "twitter.com/i/web/status/9…",
            "start": 110,
            "end": 133
        }],
        "hashtagEntities": [],
        "mediaEntities": [],
        "symbolEntities": [],
        "currentUserRetweetId": -1,
        "user": {
            "id": 2294278176,
            "name": "Cricket on BT Sport",
            "screenName": "btsportcricket",
            "location": "The Gabba",
            "description": "Watch the ODI series between England and Australia on BT Sport. Also the home of the @BBL!",
            "descriptionURLEntities": [],
            "urlEntity": {
                "url": "https://t.co/Flc9k1FSfd",
                "expandedURL": "http://sport.bt.com/cricket-01364050608536",
                "displayURL": "sport.bt.com/cricket-013640…",
                "start": 0,
                "end": 23
            },
            "isContributorsEnabled": false,
            "profileImageUrl": "http://pbs.twimg.com/profile_images/950730480139333632/nutJD8hz_normal.jpg",
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/950730480139333632/nutJD8hz_normal.jpg",
            "isDefaultProfileImage": false,
            "url": "https://t.co/Flc9k1FSfd",
            "isProtected": false,
            "followersCount": 44554,
            "profileBackgroundColor": "DADEE1",
            "profileTextColor": "333333",
            "profileLinkColor": "FF0000",
            "profileSidebarFillColor": "DDEEF6",
            "profileSidebarBorderColor": "FFFFFF",
            "profileUseBackgroundImage": true,
            "isDefaultProfile": false,
            "showAllInlineMedia": false,
            "friendsCount": 277,
            "createdAt": "Jan 16, 2014 4:43:49 PM",
            "favouritesCount": 965,
            "utcOffset": 0,
            "timeZone": "London",
            "profileBackgroundImageUrl": "http://pbs.twimg.com/profile_background_images/431758204016406528/QEZ9zTOo.jpeg",
            "profileBackgroundImageUrlHttps": "https://pbs.twimg.com/profile_background_images/431758204016406528/QEZ9zTOo.jpeg",
            "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/2294278176/1515928782",
            "profileBackgroundTiled": false,
            "lang": "en",
            "statusesCount": 3822,
            "isGeoEnabled": false,
            "isVerified": true,
            "translator": false,
            "listedCount": 212,
            "isFollowRequestSent": false
        },
        "quotedStatusId": -1
    },
    "userMentionEntities": [{
        "name": "Cricket on BT Sport",
        "screenName": "btsportcricket",
        "id": 2294278176,
        "start": 3,
        "end": 18
    }],
    "urlEntities": [],
    "hashtagEntities": [{
        "text": "AUSvENG",
        "start": 130,
        "end": 138
    }],
    "mediaEntities": [],
    "symbolEntities": [],
    "currentUserRetweetId": -1,
    "user": {
        "id": 1782534222,
        "name": "Stable Genius",
        "screenName": "albeesko",
        "location": "NJIT",
        "description": "A lifetime of glory is worth a moment of pain",
        "descriptionURLEntities": [],
        "isContributorsEnabled": false,
        "profileImageUrl": "http://pbs.twimg.com/profile_images/945735959693484032/N_Mr2N6S_normal.jpg",
        "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/945735959693484032/N_Mr2N6S_normal.jpg",
        "isDefaultProfileImage": false,
        "isProtected": false,
        "followersCount": 320,
        "profileBackgroundColor": "C0DEED",
        "profileTextColor": "333333",
        "profileLinkColor": "1DA1F2",
        "profileSidebarFillColor": "DDEEF6",
        "profileSidebarBorderColor": "C0DEED",
        "profileUseBackgroundImage": true,
        "isDefaultProfile": true,
        "showAllInlineMedia": false,
        "friendsCount": 296,
        "createdAt": "Sep 8, 2013 4:06:34 AM",
        "favouritesCount": 4148,
        "utcOffset": -1,
        "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/1782534222/1512017029",
        "profileBackgroundTiled": false,
        "lang": "en",
        "statusesCount": 14231,
        "isGeoEnabled": false,
        "isVerified": false,
        "translator": false,
        "listedCount": 0,
        "isFollowRequestSent": false
    },
    "quotedStatusId": -1
}, {
    "createdAt": "Jan 20, 2018 8:34:09 AM",
    "id": 954550084397498368,
    "text": "RT @Cricketpolls3: Which batter has impressed you the most in the recent couple 9f matches in #AUSvENG ?",
    "displayTextRangeStart": -1,
    "displayTextRangeEnd": -1,
    "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
    "isTruncated": false,
    "inReplyToStatusId": -1,
    "inReplyToUserId": -1,
    "isFavorited": false,
    "isRetweeted": false,
    "favoriteCount": 0,
    "retweetCount": 2,
    "isPossiblySensitive": false,
    "lang": "en",
    "contributorsIDs": [],
    "retweetedStatus": {
        "createdAt": "Jan 19, 2018 7:00:58 PM",
        "id": 954345439259578368,
        "text": "Which batter has impressed you the most in the recent couple 9f matches in #AUSvENG ?",
        "displayTextRangeStart": -1,
        "displayTextRangeEnd": -1,
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
        "isTruncated": false,
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "isFavorited": false,
        "isRetweeted": false,
        "favoriteCount": 1,
        "retweetCount": 2,
        "isPossiblySensitive": false,
        "lang": "en",
        "contributorsIDs": [],
        "userMentionEntities": [],
        "urlEntities": [],
        "hashtagEntities": [{
            "text": "AUSvENG",
            "start": 75,
            "end": 83
        }],
        "mediaEntities": [],
        "symbolEntities": [],
        "currentUserRetweetId": -1,
        "user": {
            "id": 923387282849009665,
            "name": "Cricket polls",
            "screenName": "Cricketpolls3",
            "location": "Where that six landed",
            "description": "Keep scrolling down there are #polls waiting for you..\nFollow us for Polls,#scores,latest #cricket #events,#information,#talk,#facts and alot more..",
            "descriptionURLEntities": [],
            "isContributorsEnabled": false,
            "profileImageUrl": "http://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
            "isDefaultProfileImage": false,
            "isProtected": false,
            "followersCount": 135,
            "profileBackgroundColor": "F5F8FA",
            "profileTextColor": "333333",
            "profileLinkColor": "1DA1F2",
            "profileSidebarFillColor": "DDEEF6",
            "profileSidebarBorderColor": "C0DEED",
            "profileUseBackgroundImage": true,
            "isDefaultProfile": true,
            "showAllInlineMedia": false,
            "friendsCount": 79,
            "createdAt": "Oct 26, 2017 8:44:18 AM",
            "favouritesCount": 945,
            "utcOffset": -1,
            "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/923387282849009665/1515905099",
            "profileBackgroundTiled": false,
            "lang": "en",
            "statusesCount": 1111,
            "isGeoEnabled": false,
            "isVerified": false,
            "translator": false,
            "listedCount": 1,
            "isFollowRequestSent": false
        },
        "quotedStatusId": -1
    },
    "userMentionEntities": [{
        "name": "Cricket polls",
        "screenName": "Cricketpolls3",
        "id": 923387282849009665,
        "start": 3,
        "end": 17
    }],
    "urlEntities": [],
    "hashtagEntities": [{
        "text": "AUSvENG",
        "start": 94,
        "end": 102
    }],
    "mediaEntities": [],
    "symbolEntities": [],
    "currentUserRetweetId": -1,
    "user": {
        "id": 3268344722,
        "name": "Girish sharma",
        "screenName": "Girishs10883782",
        "location": "Jaipur, India",
        "description": "Chech out @cricketpolls3 !!",
        "descriptionURLEntities": [],
        "urlEntity": {
            "url": "https://t.co/YTs1tCotRH",
            "expandedURL": "http://anastrogeek.WordPress.com",
            "displayURL": "anastrogeek.WordPress.com",
            "start": 0,
            "end": 23
        },
        "isContributorsEnabled": false,
        "profileImageUrl": "http://pbs.twimg.com/profile_images/867025617937674240/Nb0wpYya_normal.jpg",
        "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/867025617937674240/Nb0wpYya_normal.jpg",
        "isDefaultProfileImage": false,
        "url": "https://t.co/YTs1tCotRH",
        "isProtected": false,
        "followersCount": 36,
        "profileBackgroundColor": "C0DEED",
        "profileTextColor": "333333",
        "profileLinkColor": "1DA1F2",
        "profileSidebarFillColor": "DDEEF6",
        "profileSidebarBorderColor": "C0DEED",
        "profileUseBackgroundImage": true,
        "isDefaultProfile": true,
        "showAllInlineMedia": false,
        "friendsCount": 218,
        "createdAt": "Jul 4, 2015 11:48:14 PM",
        "favouritesCount": 1361,
        "utcOffset": -1,
        "profileBackgroundImageUrl": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBackgroundImageUrlHttps": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/3268344722/1495549988",
        "profileBackgroundTiled": false,
        "lang": "en",
        "statusesCount": 458,
        "isGeoEnabled": false,
        "isVerified": false,
        "translator": false,
        "listedCount": 0,
        "isFollowRequestSent": false
    },
    "quotedStatusId": -1
}, {
    "createdAt": "Jan 20, 2018 8:31:48 AM",
    "id": 954549491461320704,
    "text": "RT @Cricketpolls3: Which batter has impressed you the most in the recent couple 9f matches in #AUSvENG ?",
    "displayTextRangeStart": -1,
    "displayTextRangeEnd": -1,
    "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
    "isTruncated": false,
    "inReplyToStatusId": -1,
    "inReplyToUserId": -1,
    "isFavorited": false,
    "isRetweeted": false,
    "favoriteCount": 0,
    "retweetCount": 2,
    "isPossiblySensitive": false,
    "lang": "en",
    "contributorsIDs": [],
    "retweetedStatus": {
        "createdAt": "Jan 19, 2018 7:00:58 PM",
        "id": 954345439259578368,
        "text": "Which batter has impressed you the most in the recent couple 9f matches in #AUSvENG ?",
        "displayTextRangeStart": -1,
        "displayTextRangeEnd": -1,
        "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Lite</a>",
        "isTruncated": false,
        "inReplyToStatusId": -1,
        "inReplyToUserId": -1,
        "isFavorited": false,
        "isRetweeted": false,
        "favoriteCount": 1,
        "retweetCount": 2,
        "isPossiblySensitive": false,
        "lang": "en",
        "contributorsIDs": [],
        "userMentionEntities": [],
        "urlEntities": [],
        "hashtagEntities": [{
            "text": "AUSvENG",
            "start": 75,
            "end": 83
        }],
        "mediaEntities": [],
        "symbolEntities": [],
        "currentUserRetweetId": -1,
        "user": {
            "id": 923387282849009665,
            "name": "Cricket polls",
            "screenName": "Cricketpolls3",
            "location": "Where that six landed",
            "description": "Keep scrolling down there are #polls waiting for you..\nFollow us for Polls,#scores,latest #cricket #events,#information,#talk,#facts and alot more..",
            "descriptionURLEntities": [],
            "isContributorsEnabled": false,
            "profileImageUrl": "http://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
            "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
            "isDefaultProfileImage": false,
            "isProtected": false,
            "followersCount": 135,
            "profileBackgroundColor": "F5F8FA",
            "profileTextColor": "333333",
            "profileLinkColor": "1DA1F2",
            "profileSidebarFillColor": "DDEEF6",
            "profileSidebarBorderColor": "C0DEED",
            "profileUseBackgroundImage": true,
            "isDefaultProfile": true,
            "showAllInlineMedia": false,
            "friendsCount": 79,
            "createdAt": "Oct 26, 2017 8:44:18 AM",
            "favouritesCount": 945,
            "utcOffset": -1,
            "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/923387282849009665/1515905099",
            "profileBackgroundTiled": false,
            "lang": "en",
            "statusesCount": 1111,
            "isGeoEnabled": false,
            "isVerified": false,
            "translator": false,
            "listedCount": 1,
            "isFollowRequestSent": false
        },
        "quotedStatusId": -1
    },
    "userMentionEntities": [{
        "name": "Cricket polls",
        "screenName": "Cricketpolls3",
        "id": 923387282849009665,
        "start": 3,
        "end": 17
    }],
    "urlEntities": [],
    "hashtagEntities": [{
        "text": "AUSvENG",
        "start": 94,
        "end": 102
    }],
    "mediaEntities": [],
    "symbolEntities": [],
    "currentUserRetweetId": -1,
    "user": {
        "id": 923387282849009665,
        "name": "Cricket polls",
        "screenName": "Cricketpolls3",
        "location": "Where that six landed",
        "description": "Keep scrolling down there are #polls waiting for you..\nFollow us for Polls,#scores,latest #cricket #events,#information,#talk,#facts and alot more..",
        "descriptionURLEntities": [],
        "isContributorsEnabled": false,
        "profileImageUrl": "http://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
        "profileImageUrlHttps": "https://pbs.twimg.com/profile_images/932072689694425088/fwklqkAN_normal.jpg",
        "isDefaultProfileImage": false,
        "isProtected": false,
        "followersCount": 135,
        "profileBackgroundColor": "F5F8FA",
        "profileTextColor": "333333",
        "profileLinkColor": "1DA1F2",
        "profileSidebarFillColor": "DDEEF6",
        "profileSidebarBorderColor": "C0DEED",
        "profileUseBackgroundImage": true,
        "isDefaultProfile": true,
        "showAllInlineMedia": false,
        "friendsCount": 79,
        "createdAt": "Oct 26, 2017 8:44:18 AM",
        "favouritesCount": 945,
        "utcOffset": -1,
        "profileBannerImageUrl": "https://pbs.twimg.com/profile_banners/923387282849009665/1515905099",
        "profileBackgroundTiled": false,
        "lang": "en",
        "statusesCount": 1111,
        "isGeoEnabled": false,
        "isVerified": false,
        "translator": false,
        "listedCount": 1,
        "isFollowRequestSent": false
    },
    "quotedStatusId": -1
}
], "__next": "http://services.odata.org/V2/Northwind/Northwind.svc/Products?$skiptoken=20"
  }
  }




  getTweetList(top:number,skip:number){
    if(this.getTweetCount()>skip+top){
      return this.tweetList.d.results.slice(skip+1,skip+top+1);
    }else{
      return this.tweetList.d.results.slice(skip+1);
    }
  }



  getTweetCount(){
    return this.tweetList.d.results.length;
  }
}
